version: '3'

services:
  postgres:
    image: sayitsocial/postgis:${TAG_PG}
    env_file:
      - postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
  reactapp:
    image: ghcr.io/sayitsocial/front-react:${TAG_REACT}
    volumes:
      - reactapp:/data
    ports: 
      - 7888:80
  sayitsocialgo:
    image: ghcr.io/sayitsocial/sayitsocial_go:${TAG_GO}
    env_file:
      - goapp.env
    ports: 
      - 8000:8000
    volumes:
      - reactapp:/dist/web/v2/build
    depends_on:
      - postgres
    restart: always
    links:
      - "postgres:database"

volumes:
  pgdata:
    external: false
  reactapp:
    external: false


